In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,classification_report,confusion_matrix

In [3]:
df=sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [6]:
df.shape

(891, 15)

In [7]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [8]:
df["sex"].value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [9]:
df.groupby("sex")["age"].median()

sex
female    27.0
male      29.0
Name: age, dtype: float64

In [10]:
df["age"] = df["age"].fillna(df["sex"].map(df.groupby("sex")["age"].median()))
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [11]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [12]:
df["embarked"].value_counts()

embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [13]:
df["embarked"]=df["embarked"].fillna("S")

In [14]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age              0
sibsp            0
parch            0
fare             0
embarked         0
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [15]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [16]:
df.drop(columns=["deck","alive","embark_town","class"],inplace=True)
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,who,adult_male,alone
0,0,3,male,22.0,1,0,7.2500,S,man,True,False
1,1,1,female,38.0,1,0,71.2833,C,woman,False,False
2,1,3,female,26.0,0,0,7.9250,S,woman,False,True
3,1,1,female,35.0,1,0,53.1000,S,woman,False,False
4,0,3,male,35.0,0,0,8.0500,S,man,True,True

In [17]:
df=pd.get_dummies(df,columns=["who"],drop_first=True)
df=pd.get_dummies(df,columns=["embarked"],drop_first=True)
df["sex"]=df["sex"].map({"male":0,"female":1})

In [18]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,alone,who_man,who_woman,embarked_Q,embarked_S
0,0,3,0,22.0,1,0,7.2500,True,False,True,False,False,True
1,1,1,1,38.0,1,0,71.2833,False,False,False,True,False,False
2,1,3,1,26.0,0,0,7.9250,False,True,False,True,False,True
3,1,1,1,35.0,1,0,53.1000,False,False,False,True,False,True
4,0,3,0,35.0,0,0,8.0500,True,True,True,False,False,True

In [19]:
X=df.drop(columns=["survived"])
y=df["survived"]

In [20]:
X

,pclass,sex,age,sibsp,parch,fare,adult_male,alone,who_man,who_woman,embarked_Q,embarked_S
0,3,0,22.0,1,0,7.2500,True,False,True,False,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,True,False,False
2,3,1,26.0,0,0,7.9250,False,True,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,True,False,True
4,3,0,35.0,0,0,8.0500,True,True,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...
886,2,0,27.0,0,0,13.0000,True,True,True,False,False,True
887,1,1,19.0,0,0,30.0000,False,True,False,True,False,True
888,3,1,27.0,1,2,23.4500,False,False,False,True,False,True
889,1,0,26.0,0,0,30.0000,True,True,True,False,False,False
890,3,0,32.0,0,0,7.7500,True,True,True,False,True,False

In [21]:
y

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: survived, Length: 891, dtype: int64

In [22]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,
                        random_state=42,stratify=y)

In [23]:
model=LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)
y_pred=model.predict(X_test)

In [26]:
print("Accuracy is",accuracy_score(y_test,y_pred))
print("Precision is",precision_score(y_test,y_pred))
print("recall is",recall_score(y_test,y_pred))
print("f1 is",f1_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print("Confusion Matrix\n",confusion_matrix(y_test,y_pred))

Accuracy is 0.8324022346368715
Precision is 0.8095238095238095
recall is 0.7391304347826086
f1 is 0.7727272727272727
              precision    recall  f1-score   support

           0       0.84      0.89      0.87       110
           1       0.81      0.74      0.77        69

    accuracy                           0.83       179
   macro avg       0.83      0.82      0.82       179
weighted avg       0.83      0.83      0.83       179

Confusion Matrix
 [[98 12]
 [18 51]]

In [27]:
import gradio as gr
app = gr.Interface(
    fn=lambda *values:("Survived"
        if model.predict(pd.DataFrame([values], columns=X.columns))[0] == 1
        else "Not Survived"
    ),
    inputs=[gr.Number(label=col) for col in X.columns],
    outputs="text",
    title="Titanic Survival Prediction"
)

app.launch(share=True)

* Running on local URL:  http://127.0.0.1:7862
* Running on public URL: https://e6fa9a394cff47714e.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)